# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

env:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true


# We have some warnings due to Misztal's binaries
# This avoids issuing an error  
warnings_are_errors: false
sudo: required
cache: packages

r_build_args: --no-build-vignettes

r_check_args: --no-vignettes   # takes too long

r_binary_packages: 
  - Matrix
  - ggplot2
  - lme4
  - nlme
  - reshape2
  - MASS
  - plyr
  - testthat

before_install:
  ## These are needed as pre-requisites for installing INLA
  - Rscript -e "install.packages(c('sp', 'Matrix', 'shiny'), repos = 'http://cran.rstudio.com/')"
  - Rscript -e "install.packages('INLA', repos = 'http://inla.r-inla-download.org/R/testing')"
